images: Mirror openshift containers on quay.io
cockpit-project/bots pull request #1790
Opened 2021-03-12 08:38 UTC by mvollmer

To avoid the rate limit.  docker.io seems to be dead when it comes to openshift containers, but hey.

2021-03-12 08:40 UTC, cockpituous commented
image-refresh in progress on 4-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-1790-20210312-083939/

2021-03-12 08:50 UTC, martinpitt requested changes
As mentioned on IRC, this IMHO makes no sense. The images on docker.io are dead (last update 3 years ago). Short-term we can just drop the automatic refresh of our openshift image, and then the current image is "it" until RHEL 7 EOL. (We already have that case with the ovirt image).

Alternatively, we find which of the [bazillion openshift images on quay.io](https://quay.io/organization/openshift/) is a good replacement (origin-cli seems like a good first start), and use these.

2021-03-12 08:51 UTC, cockpituous commented
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1790-20210312-083939/

2021-03-12 08:58 UTC, mvollmer commented
> As mentioned on IRC, this IMHO makes no sense. 

This is just applying our usual mirror machinery to get around the docker.io rate limiting, and it was relatively easy to do without much thinking.  If it works, we are back at the status quo, which allows us at least to change the openshift.setup script in random places if we need to, even if the images we pull are outdated.

*shrug*

2021-03-12 08:59 UTC, cockpituous commented
image-refresh in progress on 2-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-1790-20210312-085959/

2021-03-12 09:10 UTC, cockpituous commented
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1790-20210312-085959/

2021-03-12 09:11 UTC, cockpituous commented
image-refresh in progress on 4-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-1790-20210312-091111/

2021-03-12 09:28 UTC, cockpituous commented
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1790-20210312-091111/

2021-03-12 10:54 UTC, cockpituous commented
image-refresh in progress on 4-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-1790-20210312-105353/

2021-03-12 11:19 UTC, cockpituous commented
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1790-20210312-105353/

2021-04-07 06:23 UTC, marusak commented
Not the way we want to go.

2021-04-07 06:23 UTC, closed without merging