Add sshpass to TEST_PACKAGES for machines migration tests
cockpit-project/bots pull request #1944
Opened 2021-04-21 00:44 UTC by skobyda

I use sshpass to set up key authentication between machines for migration tests for cockpit-machines https://github.com/cockpit-project/cockpit-machines/pull/15

 * [ ] image-refresh centos-8-stream
 * [ ] image-refresh rhel-8-5
 * [ ] image-refresh rhel-9-0
 * [ ] image-refresh ubuntu-2004
 * [ ] image-refresh ubuntu-stable
 * [ ] image-refresh debian-stable
 * [ ] image-refresh debian-testing

2021-04-21 00:45 UTC, cockpituous commented
image-refresh in progress on 2-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1944-20210421-004545/

2021-04-21 00:52 UTC, cockpituous commented
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1944-20210421-004545/

2021-04-21 00:53 UTC, cockpituous commented
image-refresh in progress on 2-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1944-20210421-005353/

2021-04-21 00:55 UTC, cockpituous commented
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1944-20210421-005353/

2021-04-21 00:55 UTC, cockpituous commented
image-refresh in progress on 2-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1944-20210421-005555/

2021-04-21 00:55 UTC, cockpituous commented
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1944-20210421-005555/

2021-04-21 00:55 UTC, cockpituous commented
image-refresh in progress on 1-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-1944-20210421-005555/

2021-04-21 01:12 UTC, cockpituous commented
image-refresh ubuntu-2004 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2004-20210421-011212

2021-04-21 01:12 UTC, cockpituous commented
image-refresh in progress on 1-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-1944-20210421-011212/

2021-04-21 01:30 UTC, cockpituous commented
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20210421-013030

2021-04-21 01:30 UTC, cockpituous commented
image-refresh in progress on 1-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-1944-20210421-013030/

2021-04-21 01:44 UTC, cockpituous commented
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20210421-014444

2021-04-21 01:44 UTC, cockpituous commented
image-refresh in progress on centosci-tasks-5cbjj.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-1944-20210421-014444/

2021-04-21 01:59 UTC, cockpituous commented
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20210421-015959

2021-04-21 04:15 UTC, martinpitt requested changes
sshpass [does not exist in CentOS/RHEL 8](https://logs.cockpit-project.org/logs/image-refresh-1944-20210421-004545/log).

But this feels a bit dubious, why do you need this? If the tests set up VMs through some `m.execute()` calls, then just use the root or admin accounts, or install an SSH public key. If that's testing through the UI, then using sshpass is cheating -- are we missing some dialog where the user can type a password?

2021-04-21 04:19 UTC, martinpitt commented
Also, it's easy enough to do without:
```
echo 'echo foobar' > /tmp/askpass
chmod a+x /tmp/askpass
SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=/tmp/askpass ssh test@host
```

2021-04-21 11:43 UTC, skobyda commented
> Also, it's easy enough to do without:
> 
> ```
> echo 'echo foobar' > /tmp/askpass
> chmod a+x /tmp/askpass
> SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=/tmp/askpass ssh test@host
> ```

I don't ssh directly, I used the sshpass in order to set up key authentication with the command ssh-copy-id.
Your solution would also work but only works on fedora. On Rhel and Debian, it still prompts for a password
https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-15-20210421-111812-b1645027-debian-stable/log.html#51

2021-04-21 12:40 UTC, skobyda commented
Oh so I tried to test it locally, and your command works locally for centos-8-stream, but still fails tests in https://github.com/cockpit-project/cockpit-machines/pull/15

2021-04-21 12:47 UTC, martinpitt commented
Mentioned on IRC, but FTR:

The test can .execute() and .upload() and .download() stuff from all involved VMs. You can copy the private SSH key to one VM, so that this can ssh to the other one directly. That seems a lot easier than all the hassle with passwords and ssh-copy-id.

2021-04-22 07:45 UTC, martinpitt commented
@skobyda : How is your test looking? Can we close this PR? (it blocks quite a lot of image refreshes)

2021-04-22 12:15 UTC, skobyda commented
> @skobyda : How is your test looking? Can we close this PR? (it blocks quite a lot of image refreshes)

It works without sshpass, so we can close this PR

2021-04-22 12:15 UTC, closed without merging