naughty: adjust podman test expected failure
cockpit-project/bots pull request #2297
Opened 2021-08-11 15:40 UTC by KKoukiou

2021-08-11 16:21 UTC, marusak requested changes
Hmm, this is one of those annoying ones, where we need to land this on the right time - which still won't be the right time as downstream still needs the old pattern.
How about creating a new pattern for the same issue? It is fine to have two patterns and naughty-prune can remove both of them, once it is fixed.

2021-08-12 07:12 UTC, mvollmer commented
I'll trigger a test run in https://github.com/cockpit-project/cockpit-podman/pull/743

2021-08-12 07:13 UTC, mvollmer commented
Test in https://github.com/cockpit-project/cockpit-podman/pull/743 is green, thanks!

2021-08-12 07:13 UTC, mvollmer approved these changes

2021-08-12 07:16 UTC, merged