log.html: fix constify/assignment issue
cockpit-project/bots pull request #3065
Opened 2022-03-14 13:14 UTC by jelly

In 4f3502cc93e5cd696234dc9 log.html was ported from jQuery to vanilla
javascript which introduced two bugs. link_patterns is re-assigned when
the json data is successfully fetched.

2022-03-14 13:43 UTC, mvollmer requested changes

2022-03-14 13:43 UTC, mvollmer commented on task/log.html
> +        messageElem.text = status.message;
This needs to be `messageElem.innerText = ...`

2022-03-14 13:43 UTC, mvollmer commented on task/log.html
> +        messageElem.text = status.message;
Also, `#status` needs to be display further below, not `#message`:

```document.querySelector('#status').style.display = '';```

2022-03-15 07:41 UTC, martinpitt commented
https://logs.cockpit-project.org/logs/pull-622-20220315-064749-254704d7-fedora-35/log.html has current main's log.html which has broken pixel test refs. I copied this updated log file to the sink: https://logs.cockpit-project.org/logs/pull-622-20220315-064749-254704d7-fedora-35/log-3065.html . Et voilà, pixel refs work again \o/ Thanks @jelly !

2022-03-15 07:43 UTC, mvollmer approved these changes

2022-03-15 07:58 UTC, merged

2022-03-15 07:58 UTC, jelly commented
> 

Sorry for breaking it in the first place ;-)