setup-deploy-keys: Add cockpit release keys for website and ws container
cockpit-project/bots pull request #3410
Opened 2022-05-19 12:16 UTC by martinpitt

At the moment, cockpit's release (ab)use the Fedora SSH key to commit to
the cockpit-container repo (through release-dockerhub) and the website
(through release-guide). Let's replace these with proper deploy keys.

Updating the guide only depends on the source tarball, so this part can
and should stay in the primary release workflow -- hence, add it to the
release environment. Use the `+` syntax to avoid deleting the existing
secrets there.

Updating cockpit-container will have to wait for the COPR or Fedora koji
build to finish, and thus will likely happen asynchronously soon -- not
right inside the "release" workflow. In anticipation of that, put the
deploy key into a separate new "container-release" environment.

2022-05-19 12:16 UTC, martinpitt commented
I did *not* roll this out yet, I'd first like to get @allisonkarlitskaya 's initial opinion.

2022-05-19 14:23 UTC, allisonkarlitskaya requested changes

2022-05-19 19:06 UTC, martinpitt commented on setup-deploy-keys
> +        +cockpit-project/cockpit/release/WEBSITE_DEPLOY_KEY
The release environment also has other secrets which are not deploy keys, and I didn't want this script to delete them. I thought that's what the + was for?

We can actually remove all the existing ones after landing https://github.com/cockpit-project/cockpit/pull/17356, as that will make the remaining non-deploykey secrets obsolete. So I suppose I could drop the + already.

2022-05-19 20:03 UTC, allisonkarlitskaya commented on setup-deploy-keys
> +        +cockpit-project/cockpit/release/WEBSITE_DEPLOY_KEY
The `+` is about not deleting other deploy keys on the receiver side.  Honestly, this approach was a dead end, and we should probably remove the feature at this point.

2022-05-20 15:29 UTC, martinpitt commented on setup-deploy-keys
> +        +cockpit-project/cockpit/release/WEBSITE_DEPLOY_KEY
Ack, dropped.

2022-05-20 15:43 UTC, allisonkarlitskaya approved these changes

2022-05-20 15:43 UTC, merged

2022-05-20 16:07 UTC, martinpitt commented
Rolled out.