lib: Enable fedora-37 tests for Cockpit
cockpit-project/bots pull request #3807
Opened 2022-09-01 06:53 UTC by martinpitt

I fixed the bulk of issues in https://github.com/cockpit-project/cockpit/pull/17690 and https://github.com/cockpit-project/bots/pull/3801 (plus a few smaller ones), so this by and large works now. However, I still saw [random timeouts](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17690-20220831-125954-2a247b8a-fedora-37/log.html). My suspicion is that current F37 still has rawhide's debug kernel, which [makes everything slow](https://lists.fedoraproject.org/archives/list/devel%40lists.fedoraproject.org/thread/HRJT4UF35MRJ7C4ZXVHBFXB4BTW64YSO/). So we may need to wait with this until it gets a proper kernel.

However, I'll spin the tests a few times here to get some data.

2022-09-01 08:11 UTC, martinpitt commented
[That went well](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3807-20220901-065404-73c8d5e2-fedora-37-cockpit-project-cockpit/log.html), retrying to give it another round.

2022-09-01 08:49 UTC, martinpitt commented
Ah, there it is -- the [next run has some random timeouts again](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3807-20220901-081216-73c8d5e2-fedora-37-cockpit-project-cockpit/log.html). So let's block this for a while.

2022-09-01 13:39 UTC, martinpitt commented
Curiously that's the same failure mode as in [this PR](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17698-20220901-124102-fbbc19cc-debian-testing/log.html#32-2), which is unrelated. I wonder if something just generally became slower?

2022-09-05 09:04 UTC, mvollmer approved these changes
Yes, I agree that the timeouts don't look fedora-37 specific.

2022-09-05 09:07 UTC, mvollmer requested changes
Upps, I messed this up by trying out the "Resolve conflicts" button in Github... sorry. :-(

2022-09-05 09:21 UTC, mvollmer approved these changes

2022-09-05 09:29 UTC, merged