image-create: increase boot timeout on Arch Linux
cockpit-project/bots pull request #4154
Opened 2022-12-12 12:38 UTC by jelly

The one time `reflector-init` service blocks sshd from starting and can take quite a while to complete as it sequentially checks every mirrors repository database.

 * [ ] image-refresh arch

2022-12-12 12:41 UTC, cockpituous commented
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20221212-124141.log

2022-12-12 13:26 UTC, cockpituous commented
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20221212-132626.log

2022-12-12 13:49 UTC, cockpituous commented
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20221212-134949.log

2022-12-12 15:55 UTC, cockpituous commented
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20221212-155520

2022-12-12 15:55 UTC, cockpituous commented
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20221212-155555.log

2022-12-12 17:35 UTC, cockpituous commented
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20221212-173527

2022-12-12 17:50 UTC, martinpitt commented
Thanks @jelly ! Please push the new image here and let the tests run -- still too early to review

2022-12-12 17:50 UTC, martinpitt requested changes

2022-12-12 17:50 UTC, martinpitt commented on image-create
> +            # except with arch, the `reflector-init` service blocks ssh and it takes quite a while to
Please add a `HACK:` prefix here, to include that in greps.

2022-12-12 22:39 UTC, martinpitt commented
Ugh, this is a sea of red and "Unable to reach machine arch-127.0.0.2-2501 via ssh: 127.0.0.2:2501".

2022-12-13 12:46 UTC, jelly commented
Pulled the image down, ran ./test/image-prepare arch but `./test/verify/check-connection -vst TestConnection.testSocket` works fine here.

2023-01-05 12:40 UTC, jelly commented
The new arch image no longer uses reflector so this is unrequired.

2023-01-05 12:40 UTC, closed without merging