Test scan tests
cockpit-project/bots pull request #5177
Opened 2023-08-29 11:40 UTC by jelly

2023-08-30 14:24 UTC, jelly commented on task/test-tests-scan
> +        self.assertIsNone(stderr)
nitpick, `ifmain` is missinghere.

2023-08-30 14:55 UTC, martinpitt requested changes
Very nice!

2023-08-30 14:55 UTC, martinpitt commented on task/test-tests-scan
> +        print([script, *args])
debugging leftover

2023-08-30 14:55 UTC, martinpitt commented on task/test-tests-scan
> +        return " ".join(expected_output.splitlines()).strip()
Maybe better to use this style:
```python
expected_output = ("first "
                   "second")
```
then you can avoid this split/strip/join hack

2023-08-31 08:38 UTC, martinpitt approved these changes
Very cool, thanks!

2023-08-31 08:38 UTC, merged