naughty: handle fnmatch regex behaviour on Python 3.9
cockpit-project/bots pull request #5475
Opened 2023-10-30 14:47 UTC by jelly

On Python 3.9 fnmatch cannot handle ["check-foo"] and gives an exception.

See https://github.com/cockpit-project/cockpit/pull/17226

2023-10-30 15:12 UTC, martinpitt requested changes

2023-10-31 09:07 UTC, jelly commented on naughty/arch/5106-journalctl-since-until-behaviour-change-2
> +        })(["January 1, 2037", ["check*journal", "AFTER BOOT", ""], ["", "Reboot", ""], ["check*journal", "BEFORE BOOT", ""]])): Uncaught (in promise) Error: condition did not become true
Sure

2023-10-31 09:07 UTC, jelly commented on naughty/arch/5106-journalctl-since-until-behaviour-change-2
> +        })(["January 1, 2037", ["check*journal", "AFTER BOOT", ""], ["", "Reboot", ""], ["check*journal", "BEFORE BOOT", ""]])): Uncaught (in promise) Error: condition did not become true
Can we test this against centos-9-stream/fedora-39 here? That would be nice I think

2023-10-31 09:13 UTC, martinpitt commented on naughty/arch/5106-journalctl-since-until-behaviour-change-2
> +        })(["January 1, 2037", ["check*journal", "AFTER BOOT", ""], ["", "Reboot", ""], ["check*journal", "BEFORE BOOT", ""]])): Uncaught (in promise) Error: condition did not become true
We can't run against TF (that needs to happen in cockpit, or tested locally), but you can/should trigger c9s/f39 tests against cockpit here.

2023-10-31 09:17 UTC, jelly commented on naughty/arch/5106-journalctl-since-until-behaviour-change-2
> +        })(["January 1, 2037", ["check*journal", "AFTER BOOT", ""], ["", "Reboot", ""], ["check*journal", "BEFORE BOOT", ""]])): Uncaught (in promise) Error: condition did not become true
Woops, made the mistake of using `image:fedora-39` so triggered a bit too much.

2023-10-31 09:18 UTC, jelly commented on naughty/arch/5106-journalctl-since-until-behaviour-change-2
> +        })(["January 1, 2037", ["check*journal", "AFTER BOOT", ""], ["", "Reboot", ""], ["check*journal", "BEFORE BOOT", ""]])): Uncaught (in promise) Error: condition did not become true
c9s can't be triggered sadly:

```
[jelle@t14s][~/projects/cockpit-bots]%./tests-trigger 5475 centos-9-stream/other@cockpit-project/cockpit
ignoring unknown context centos-9-stream/other@cockpit-project/cockpit
```

2023-10-31 09:20 UTC, martinpitt approved these changes
Thanks! LGTM.

2023-10-31 09:45 UTC, jelly commented
Fedora 39 Succeeded https://cockpit-logs.us-east-1.linodeobjects.com/pull-5475-20231031-091655-bacca430-fedora-39-other-cockpit-project-cockpit/log.html

2023-10-31 10:29 UTC, merged