Introduce OpenSUSE Tumbleweed image
cockpit-project/bots pull request #6011
Opened 2024-03-04 16:09 UTC by jelly

* [x] image-refresh opensuse-tumbleweed

2024-03-04 16:14 UTC, cockpituous commented
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-opensuse-tumbleweed-20240304-161009-3bddbb0b-image-refresh-opensuse-tumbleweed/log.html

2024-03-08 08:34 UTC, cockpituous commented
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-opensuse-tumbleweed-52d111b3-20240308-082241/log.html

2024-03-20 15:44 UTC, cockpituous commented
image-refresh opensuse-tumbleweed done: https://github.com/cockpit-project/bots/commits/image-refresh-opensuse-tumbleweed-20240320-154432

2024-03-20 15:44 UTC, cockpituous commented
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-opensuse-tumbleweed-c05d91e4-20240320-153113/log.html

2024-03-20 16:31 UTC, martinpitt commented
Worked! Please cherry-pick https://github.com/cockpit-project/bots/commit/10c69bb74747c66af71250fea5be3fad684fda1e then we can do the next step and run a simple test against it. We usually start with `starter-kit`, as tests are trivial, and we can make sure that package building, installation, and starting cockpit works in general. But of course we'll leave the strategy to you.

2024-03-23 05:48 UTC, martinpitt requested changes

2024-03-23 05:48 UTC, martinpitt commented on images/scripts/lib/build-deps.sh
> +        # macro for detmerning suse version is %suse_version
Typo

2024-03-23 05:48 UTC, martinpitt commented on images/scripts/opensuse-tumbleweed.setup
> +opensuse.setup
Let's not do this indirection just yet -- if we get a second similar suse image, we can do the factorization then. The micro image setup will most likely look completely different.

2024-03-23 05:52 UTC, cockpituous commented
image-refresh opensuse-tumbleweed done: https://github.com/cockpit-project/bots/commits/image-refresh-opensuse-tumbleweed-20240323-055237

2024-03-23 05:52 UTC, cockpituous commented
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-opensuse-tumbleweed-be5a86cc-20240323-053844/log.html

2024-03-23 06:11 UTC, closed without merging