WIP: adf705fa03a7: [no-test] Image refresh for arch
cockpit-project/bots pull request #6643
Opened 2024-07-20 22:48 UTC by cockpituous

Image refresh for arch
 * [ ] image-refresh arch

2024-07-20 22:48 UTC, cockpituous commented
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240720-224801

2024-07-20 22:49 UTC, cockpituous commented
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-5b58ef51-20240720-223718/log.html

2024-07-22 14:14 UTC, tomasmatus commented
```
log: osinfo-detect command failed:  (process:5193): GLib-GIO-WARNING **: 08:01:10.590: Can't find module 'gvfs' specified in GIO_USE_VFS
```
note to self tomorrow - installing `gvfs` package seems to have fixed the failing tests, tested locally (investigate what's up?)

2024-07-22 14:53 UTC, martinpitt commented
@tomasmatus Hmm, according to the Removed/Added/Changed, gvfs didn't drop and libosinfo didn't update. gsettings-desktop-schemas was removed though -- did installing gvfs pull in some of the removed packages as a dependency? gvfs is rather heavy and a desktop package, it should preferably not be on a server image.

2024-07-23 04:42 UTC, martinpitt commented
@tomasmatus also, please check that you *don't* get that GVFS warning in the previous image and others, i.e. that it is *actually* a symptom of the regression and not just unrelated. 

For example, we've been getting that warning for many years e.g. [here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1730-e2fdd3c4-20240719-133438-rhel-9-4/log)

So my bet is that installing gvfs pulled in some other package which is an undeclared dependency of libosinfo. That should be reported to/fixed in arch, and then we can install it manually as a workaround.

Thanks!

2024-07-23 08:36 UTC, tomasmatus commented
```
+ ./image-diff /cache/images/arch-80f19ce9b6c04a1438efe4ed4eeb821f9b90139e8cc18e8cad2c90be1733e0e5.qcow2 arch
Removed:
  adobe-source-code-pro-fonts (2.042u+1.062i+1.026vf-2)
  cantarell-fonts (1:0.303.1-1)
  dconf (0.40.0-2)
  gsettings-desktop-schemas (46.0-2)
  ```
  both `dconf` and `gsettings-desktop-schemas` got pulled by the [`gvfs`](https://archlinux.org/packages/extra/x86_64/gvfs/) package. Installing [`gsettings-desktop-schema`](https://archlinux.org/packages/extra/any/gsettings-desktop-schemas/) also pulls `dconf` so it looks like both of these packages are needed.

2024-07-23 08:54 UTC, cockpituous commented
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240723-085404

2024-07-23 08:54 UTC, cockpituous commented
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-a0adcf81-20240723-084324/log.html

2024-07-23 12:01 UTC, martinpitt commented on images/scripts/arch.setup
> +gsettings-desktop-schemas \
This is highly dubious. This is totally *not* a cockpit dependency. Please report a bug against arch about this (libosinfo has a CLI which should reproduce this). libosinfo should need a desktop package, and if it really really has to, it needs to declare a dependency by itself. After that, please move this to TEST_PACKAGES with a `# HACK` comment. Thanks!

2024-07-23 12:54 UTC, cockpituous commented
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240723-125425

2024-07-23 12:54 UTC, cockpituous commented
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-f7c6989c-20240723-124311/log.html

2024-07-23 13:41 UTC, tomasmatus commented
libosinfo on arch should declare `gsettings-desktop-schemas` as a dependency

```
(process:7692): GLib-GIO-ERROR **: 08:02:38.623: Settings schema 'org.gnome.system.proxy' is not installed
log: osinfo-detect command failed:  (process:7744): GLib-GIO-WARNING **: 08:02:43.630: Can't find module 'gvfs' specified in GIO_USE_VFS
```
[full log here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6643-02ccced1-20240721-075151-arch-cockpit-project-cockpit-machines/log.html#13)

2024-07-23 15:31 UTC, martinpitt commented
@tomasmatus does that reproduce with calling `osinfo-detect` on the CLI? I.e. is that a reproducer that can be reported to arch?

2024-07-24 07:31 UTC, tomasmatus commented
@martinpitt here's the reproducer

```
[root@archlinux ~]# osinfo-detect 'https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/28/Server/x86_64/os'

(osinfo-detect:1759): GLib-GIO-ERROR **: 07:29:03.513: Settings schema 'org.gnome.system.proxy' is not installed
Trace/breakpoint trap (core dumped)
```

2024-07-24 09:52 UTC, martinpitt requested changes
Cheers, nice work! Please squash the two image refresh commits together, force-push, and trigger the tests.

2024-07-24 10:10 UTC, martinpitt approved these changes
Cheers!

2024-07-24 10:10 UTC, merged