naughty: New pattern for 7139
cockpit-project/bots pull request #7140
Opened 2024-11-25 09:52 UTC by mvollmer

2024-11-25 09:56 UTC, mvollmer commented
This should also trigger in fedora-40 already. Let's make an image right away...

2024-11-25 10:17 UTC, cockpituous commented
image-refresh fedora-40 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-40-20241125-101752

2024-11-25 10:17 UTC, cockpituous commented
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-1d76dfbd-20241125-095709/log.html

2024-11-25 10:23 UTC, martinpitt commented on naughty/fedora-40/7139-tracer-segfaults-in-the-past
> +# testBasic (__main__.TestHistoryMetrics.testBasic)
Please copy that to fedora-41 as well, see #7123

2024-11-25 10:23 UTC, martinpitt requested changes

2024-11-25 10:23 UTC, martinpitt commented on naughty/fedora-40/7139-tracer-segfaults-in-the-past
> +# testBasic (__main__.TestHistoryMetrics.testBasic)
And it also affects TestMultiCPU.testCPUUsage

2024-11-25 10:25 UTC, martinpitt commented
(Copied from the parallel image refresh #7126 -- there is no reason to believe that this refresh magically fixes any of these):

Phew, this is a big one. There's the python crashes from #21301, [files needs a pixel update](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7126-31b95e35-20241123-230312-fedora-40-cockpit-project-cockpit-files/log.html) due to the new cockpit version enabling "open in terminal", sub-man causes an oops in the same manner as in #7123, and composer failed on an internal npm mirror failure (retried that one).

2024-11-25 10:42 UTC, mvollmer commented
> (Copied from the parallel image refresh #7126 -- there is no reason to believe that this refresh magically fixes any of these):

Oops, I wasn't aware yet of that PR... sorry.

2024-11-25 11:39 UTC, mvollmer commented
> [TestMultiCPU.testCPUUsage](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7140-7b80df96-20241125-111406-fedora-40-other-cockpit-project-cockpit/log.html#39) not caught by naughty?

My mistake. Man, I am bad at multi-tasking...

2024-11-26 12:25 UTC, martinpitt commented
`sudo dnf info cockpit-bridge` shows 329.1 now, so refreshing.

2024-11-26 12:46 UTC, cockpituous commented
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-fdac239d-20241126-122414/log.html

2024-11-26 19:04 UTC, martinpitt commented
https://github.com/cockpit-project/cockpit-machines/pull/1925 landed, so retrying the machines tests. cockpit and -files only fail the pixel tests. After machines goes green, I'll land the pixel tests and then do a final rebase to land this fully green -- otherwise we'll ruin the flake statistics. It's evening and fairly quiet, so I think we can afford to do it this way.

2024-11-26 20:31 UTC, martinpitt approved these changes
:rocket: *exhale* 

Thanks @mvollmer ! Great teamwork!

2024-11-26 20:47 UTC, merged